name: Desplegar en Lambda #Nombre de workflow, asi aparece cuando se ejecuta GitHub Actions.

on: #El workflow se activa cuando se hace un git push a la rama main.
  push:
    branches:
      - main

jobs: #Se pueden tener varios jobs.

  approval:
      uses: ./.github/workflows/manual-approval.yml
      with:
        approvers: RamiParcero
      secrets:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    runs-on: ubuntu-latest #GitHub crea una VM para ejecutar el workflow.
    steps: #Dentro del job "deploy" definimos los pasos que GitHub tiene que seguir:
      - name: Checkout #Descarga el codigo del repo a la VM
        uses: actions/checkout@v3
      
      - name: Instala Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Instala dependencias
        run: npm install
      
      - name: Copia index.js y app.js a la raíz
        run: cp src/index.js src/app.js .

      - name: Empaqueta el codigo
        run: zip -r function.zip index.js app.js package.json node_modules/

      - name: Configura credenciales de AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Despliegue a AWS Lambda 
        run: |
          aws lambda update-function-code \
            --function-name Hello-World-Lambda \
            --zip-file fileb://function.zip

