name: Desplegar en Lambda #Nombre de workflow, asi aparece cuando se ejecuta GitHub Actions.

on: #El workflow se activa cuando se hace un git push a la rama main.
  push:
    branches:
      - main

jobs: #Se pueden tener varios jobs.

  build:
    name: Construye el Lambda.Zip 
    runs-on: ubuntu-latest #GitHub crea una VM para ejecutar el workflow.

    steps: #Dentro del job "deploy" definimos los pasos que GitHub tiene que seguir:
      - name: Checkout #Descarga el codigo del repo a la VM
        uses: actions/checkout@v3

      - name: Prepara Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Instala dependencias
        run: npm ci

      - name: Empaqueta el Lambda
        run: |
          mkdir lambda-package
          cp -r src lambda-package/
          cp package.json lambda-package/
          cp package-lock.json lambda-package/
          cp -r node_modules lambda-package/
          cd lambda-package
          zip -r ../lambda.zip .
          cd ..

      - name: Uploadea el artifact creado
        uses: actions/upload-artifact@v4
        with:
          name: lambda-zip
          path: lambda.zip

  approval: #llama al otro workflow que contiene el manual approval.
      uses: ./.github/workflows/manual-approval.yml
      with:
        approvers: RamiParcero
      secrets:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    name: Despliega el AWS Lambda
    runs-on: ubuntu-latest 
    needs: approval
    steps: 
      - name: Descarga el artifact
        uses: actions/download-artifact@v4
        with: 
          name: lambda.zip

      - name: Configura credenciales de AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Despliegue a AWS Lambda 
        run: |
          aws lambda update-function-code \
            --function-name Hello-World-Lambda \
            --zip-file fileb://lambda.zip

